### ISSUE TITLE
Update environment.yml with new dependencies.

### ISSUE THREAD

**Issue by vinisalazar** [vinisalazar/BioProv#20]
v0.1.13 will include a new dependency, [TinyDB](https://tinydb.readthedocs.io/), which will be the database system for BioProv.

Must update environment.yml with the following packages:
- TinyDB
- [nb_conda_kernels](https://anaconda.org/conda-forge/nb_conda_kernels)

**Comment by jvfe** [comment]
TinyDB wouldn't be necessary since it's already in the install_requires of the package, so it would get downloaded anyway when developing. 

I'll submit a simple PR soon to add nb_conda_kernels.

**Comment by vinisalazar** [comment]
Closed by #21
