### ISSUE TITLE
Add GitHub action "create-release"

### ISSUE THREAD

**Issue by vinisalazar** [vinisalazar/BioProv#22]
To make this repository citable through Zenodo, it must have GitHub release. However, creating GH releases manually is a bit time consuming. Ideally, whenever a tag gets pushed, GH should create a new release.

Create a PR that will:
- Add a [GitHub action to create a release](https://github.com/actions/create-release) when new tags are created.

**Comment by yzwdroid** [comment]
can I give it a try?

**Comment by vinisalazar** [comment]
Added in 2f76c44a554a3f3bb5f7e1f1b26ae544bf2ba38b.
