### ISSUE TITLE
Add support for ProvStore API

### ISSUE THREAD

**Issue by vinisalazar** [vinisalazar/BioProv#23]
[ProvStore](https://openprovenance.org/store/) is an open provenance repository for W3C-PROV documents. BioProv should add support for CRUD operations using the [ProvStore API](https://openprovenance.org/store/help/api/#python).

Submit a PR that will:
- Manage configuration of the ProvStore credentials [ ]
- Allow CRUD operations with the ProvStore API [ ]

**Comment by jvfe** [comment]
Do you intend to implement this as a submodule in bioprov/src or as a new module? Not that I intend to do it, just interested hahah

**Comment by vinisalazar** [comment]
This should be implemented in the bioprov/src/config.py module, but I'm open to ideas.

**Comment by jvfe** [comment]
> This should be implemented in the bioprov/src/config.py module, but I'm open to ideas.

I'm thinking the API key as an attribute of bioprov.src.config.EnvProv and the CRUD functions as methods inside of bioprov.src.main.Project. How does that sound to you? I didn't look very carefully at the src module but it's what popped into my head for solving this issue.

**Comment by vinisalazar** [comment]
Yes, that sounds great. The API key should be read from a file and stored as an attribute when the Config class is instantiated.  What will take a bit of effort is coding the behaviour of the Config class when trying to read from said file. If the file does not exist, it should prompt the user input their username and key for their ProvStore login, and automatically create the file.

**Comment by vinisalazar** [comment]
The feature has been implemented but it seems that the ProvStore API is not working properly. I have opened an issue (millar/provstore-api#8) in their repository to try to understand what might be happening.

**Comment by jvfe** [comment]
> The feature has been implemented but the ProvStore API is not working as it should. I have opened an issue ([millar/provstore-api#8](https://github.com/millar/provstore-api/issues/8)) in their repository to try to understand what is happening.

From what I can see the endpoint https://provenance.ecs.soton.ac.uk/store/api/v0 they use in the package isn't live! 

It looks like the python package isn't updated anymore, as the official documentation now points to another URL https://provenance.ecs.soton.ac.uk/store/api/v0 . Worst case scenario we can try to implement wrappers around this endpoint.

**Comment by vinisalazar** [comment]
ok
