### ISSUE TITLE
Any reason to use .format() instead of fstrings?

### ISSUE THREAD

**Issue by jvfe** [vinisalazar/BioProv#3]
Hi,

I've noticed most (if not all) string interpolation in your package uses the .format() style, instead of fstrings. I don't think it's for backwards compatibility, since your package already requires Python>=3.6 and [fstrings were implemented in 3.6](https://www.python.org/dev/peps/pep-0498/), so is it a question of personal preference using .format()? I ask because, even though there isn't a clear advantage of one over the other, I find fstrings more concise and easier to read. 

If you plan on changing them, the output of `grep -R "[\"|'].format(" .`  on the root directory would show all occurrences.

**Comment by vinisalazar** [comment]
I also prefer fstrings, and began the project using them. But then I decided to start using .format() to try to produce a 3.5 compatible version. However some fstrings remain in the code and I've largely gave up on this.

If you want to refactor .format() occurrences to fstrings, go ahead, it would be a welcome addition.

**Comment by jvfe** [comment]
Oh I see! I'll send a PR refactoring them then. Thanks!
