### ISSUE TITLE
Non-code improvements that would be nice to have

### ISSUE THREAD

**Issue by jvfe** [vinisalazar/BioProv#4]
Hi, great work on this package!

I think a few simple things that don't mess with the source code would greatly improve it:

- [x] **Adding a CONTRIBUTING.md to the root** 

This would make this repo **much** more inviting for beginners that want to contribute (Such as myself!). I really like [biopython's contribution guide](https://github.com/biopython/biopython/blob/master/CONTRIBUTING.rst), for example.

- [x] **Adding a link to the documentation in the README.**

I find the notebooks you made really nice but I've also noticed you already have some docs on [readthedocs](https://bioprov.readthedocs.io/en/latest/index.html), maybe add a [badge](https://readthedocs.org/projects/bioprov/badge/?version=latest) on the README to refer to them? Some people like this more "traditional" type of documentation hahah. And you could even turn the current notebooks into .rst to have a static version of them over there.

- [x] **Improve the project's page on PyPI**

Currently, your project page only has a very short description, even though your README is much more informative! You could try using it as your long description, [see one of my packages for example](https://pypi.org/project/reconciler/). It would only require a simple change on:

https://github.com/vinisalazar/BioProv/blob/178bef7710134f8e10d345e6cecc37b1de2e1c30/setup.py#L16-L21

- [x] **Add an environment file for development**

This one is a bit tougher, since the tests require some external software, but I believe having a conda "dev_environment.yml" file would make it a lot easier for collaborators to work on this, run tests, add features and what not. *Edit*: Thinking back on it, this isn't really necessary as long as it's well described in the contribution guidelines what packages/software is needed for testing, code styling, etc.

Sorry for this huge wall of text, they are mostly just suggestions, feel free to disregard any of them! 

That being said, I'd be happy to draft a PR to tackle the first three suggestions, if you don't mind.

**Comment by vinisalazar** [comment]
These are all welcome additions which I haven't worked on due to focusing primarily on the code itself. I will try to implement them (specially the Contributing Guidelines) by next week. If you'd like to work on any of this, go ahead, just comment here to avoid duplicated efforts.

**Comment by jvfe** [comment]
For sure, I'll try working on the first three. 

I'll draft a simple contributing guideline and you could just comment what you'd want to see on it on the PR itself or change it afterwards.

Thanks!

**Comment by vinisalazar** [comment]
I noticed that the readthedocs build is failing, apparently due to Pytest version problems. I will investigate further to see if I can get the build to pass. Here is a screenshot of the build log.

![Screen Shot 2020-10-16 at 14 49 12](https://user-images.githubusercontent.com/17276653/96291757-ea0f3480-0fbe-11eb-9c5f-5108ebf72583.png)

**Comment by jvfe** [comment]
I've had some issues with dependencies in readthedocs as well, you might have some luck adding a [readthedocs.yml](https://docs.readthedocs.io/en/latest/config-file/v2.html)

**Comment by vinisalazar** [comment]
Fixed docs build
