### ISSUE TITLE
Package requirements

### ISSUE THREAD

**Issue by maximtrp** [vinisalazar/BioProv#51]
Hello!

While reviewing your package, I have noticed that the requirements are not clearly stated anywhere (just several packages mentioned here and there). Please add such a section to your documentation and README file. You can just copy-paste the requirements from your [setup.py](https://github.com/vinisalazar/BioProv/blob/master/setup.py) file.

https://github.com/openjournals/joss-reviews/issues/3622

**Comment by vinisalazar** [comment]
Hi @maximtrp,

thank you for the issue. I have opened a PR to merge the latest version. It makes several improvements to the docs, including what you requested. I will merge it shortly.

Best,
Vini

Edit: I closed this upon the merge, but please feel free to reopen if needed.

**Comment by maximtrp** [comment]
Okay, thank you!
